#
# Copyright (c) 2013 Samsung Electronics Co., Ltd.
# 	http://www.samsung.com
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_SUNXI_SECURE_SYSTEM)	+= sunxi_crypto.o
obj-$(CONFIG_SUNXI_SECURE_SYSTEM)	+= sunxi_efuse.o

